---
title: "Checking periods"
author: "Tomasz Zielinski"
date: "2023-11-05"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r include=FALSE}
# Loading dependencies
library(tidyverse)
library(ggplot2)
library(lubridate)
library(gridExtra)
library(knitr)

```

```{r include=FALSE}
org_file = file.path("org", "15510_FFT.ppa.csv")

if (!file.exists(org_file)) {
  stop("Missing input file "+orgFile)
}

org_data = read_csv(org_file, skip = 10) 
#head(org_data)
```

```{r}
data <- org_data %>%
  separate(DataRef,into=c("ID","CELL"), sep = "\\. \\[", remove=TRUE) %>%
  separate(DataLabel,into=c("GENOTYPE","MARKER"), sep = " ", remove=FALSE) %>%
  mutate(ID, as.numeric(ID)) %>%
  mutate(DataLabel,as.factor((DataLabel))) %>%
  mutate(GENOTYPE,as.factor((GENOTYPE))) %>%
  mutate(MARKER,as.factor((MARKER))) 


data$DataLabel <- factor(data$DataLabel, levels=unique(data$DataLabel))
head(data)  

```

```{r}

g <- ggplot(data, aes(DataLabel, Period))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=DataLabel)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Period", y="[h]", x="Line")


```

```{r}

g <- ggplot(data, aes(DataLabel, Amplitude))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=MARKER)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Amplitude", x="Line")

```

```{r}

g <- ggplot(data, aes(DataLabel, Circ.PhaseToZero))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=MARKER)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Circadian phase",y='Phase [h]', x="Line")

```

```{r}


ggplot(data, aes(x = Circ.PhaseToZero, y=ERR)) + 
  #geom_polygon(fill = NA, col = 1) +
  geom_point(aes(color=DataLabel), size = 3) +
  theme_minimal() + 
  coord_polar() +
  geom_bar(stat='identity', aes(color = DataLabel, fill= DataLabel)) +
  scale_x_continuous("", breaks = 0:24, limits = c(0, 24)) #+
  #ylim(0, 1) # adjust as you like
```

Period stats
```{r}

distributions <- data %>%
  group_by(DataLabel) %>%
  summarise(avg_p=mean(Period), sd_p=sd(Period),avg_e=mean(PeriodErr), sd_e=sd(PeriodErr),avg_a=mean(Amplitude), 
            sd_a=sd(Amplitude), avg_f=mean(Circ.PhaseToZero), sd_f=sd(Circ.PhaseToZero),
            avg_rae=mean(ERR), sd_rae=sd(ERR)
            )

distributions

```

```{r}
random_data <- function(label, mean, sd, n) {
  #set.seed(123)
  
  random_values <- rnorm(n, mean = mean, sd = sd)
  random_data <- data.frame(data = rep(label, n), val = random_values)
  
  # Return the generated data frame
  return(random_data)
}

series <- function(labels, means, sds, n) {
  if (length(labels) != length(means) || length(labels) != length(sds)) {
    stop("Lengths of labels, means, and sds vectors must be the same.")
  }
  
  result_df <- data.frame(data = character(), val = numeric())
  
  for (i in seq_along(labels)) {
    label <- labels[i]
    mean_value <- means[i]
    sd_value <- sds[i]
    
    random_table <- random_data(label, mean_value, sd_value, n)
    
    result_df <- bind_rows(result_df, random_table)
  }
  
  return(result_df)
}

set.seed(124)
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(24.4, 24.5, 24.0,31.1, 30.5, 30, 22, 20, 23)
stds <- c(0.642, 0.628, 0.5, 1.25, 1.5, 1.2, 2.7, 3.5, 3.7)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to make sanity check
faked$val[faked$val < 15] <- 2 * 15 - faked$val[faked$val < 15]

faked

```


```{r}

g <- ggplot(faked, aes(data, val))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=data)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Period", y="[h]", x="Line")


```

SEED 127
```{r}
#set.seed(127)
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(24.4, 24.5, 24.0,31.1, 30.5, 30.0, 22, 20, 22)
stds <- c(0.642, 0.628, 0.7, 1.25, 1.5, 1.4, 2.7, 3.5, 3.7)

faked <- series(labels, means, stds, 8)
#faked

# reality check for periods
faked$val[faked$val < 15] <- 2 * 15 - faked$val[faked$val < 15]


periods <- faked %>% rename(Label = data, Period = val)
periods

```


```{r}

g <- ggplot(faked, aes(data, val))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=data)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Period", y="[h]", x="Line")


```


Amplitude
```{r}
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(0.14, 0.17, 0.18, 0.12, 0.15, 0.2, 0.09, 0.12, 0.13)
stds <- c(0.0151, 0.00835, 0.0214, 0.0242, 0.0226, 0.0130, 0.0130, 0.00835, 0.01)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to update the values
faked$val[faked$val < 0] <- 0 - faked$val[faked$val < 0]

#faked

g <- ggplot(faked, aes(data, val))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=data)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Amplitude", y="counts", x="Line")


amplitudes <- faked %>% rename(Label = data, Amplitude = val)
amplitudes


```


Phase
```{r}
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(4, 9.4, 15.7, 3.8, 7.2, 13.9, 3, 6, 10)
stds <- c(0.976, 1.12, 2, 1.5, 0.8, 0.7, 0.9, 3, 1.2)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to update the values
faked$val[faked$val < 0] <- 24 - faked$val[faked$val < 0]
faked$val[faked$val > 24] <- faked$val[faked$val < 24] - 24


g <- ggplot(faked, aes(data, val))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=data)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="Phase", y="counts", x="Line")


ggplot(faked, aes(x = val, y=1)) + 
  #geom_polygon(fill = NA, col = 1) +
  geom_point(aes(color=data), size = 3) +
  theme_minimal() + 
  coord_polar() +
  geom_bar(stat='identity', aes(color = data, fill= data)) +
  scale_x_continuous("", breaks = 0:24, limits = c(0, 24)) #+

phases <- faked %>% rename(Label = data, Phase = val)
phases


```

RAE
```{r}
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(0.2, 0.27, 0.18, 0.14, 0.15, 0.12, 0.4, 0.4, 0.4)
stds <- c(0.04, 0.02, 0.0214, 0.02, 0.03, 0.025, 0.12, 0.15, 0.13)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to update the values
faked$val[faked$val < 0] <- 0 - faked$val[faked$val < 0]

#faked

g <- ggplot(faked, aes(data, val))
g + # coord_cartesian(ylim=c(0, 12)) + 
  geom_boxplot(aes(fill=data)) +
  #geom_point(aes(color=GENOTYPE)) + 
  #geom_jitter(width = 0.05, aes(color=MARKER) ) +
  labs(title="RAE", y="counts", x="Line")


raes <- faked %>% rename(Label = data, RAE = val)
raes


```


```{r}

data <- periods %>%
        cbind( select(amplitudes, Amplitude)) %>%
        cbind( select(phases, Phase)) %>%
        cbind( select(raes, RAE)) %>%
        separate(Label,into=c("GENOTYPE","MARKER"), sep = " ", remove=FALSE) 


data

write_csv(data, "long_days_ppa.csv")

```

Short days

```{r}
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(24.0, 24.2, 24.5,30.1, 28.5, 28, 20, 18, 19)
stds <- c(0.642, 0.628, 0.7, 1.25, 1.5, 1.2, 2.7, 3.5, 3.7)


faked <- series(labels, means, stds, 8)
#faked

# reality check for periods
faked$val[faked$val < 15] <- 2 * 15 - faked$val[faked$val < 15]


periods <- faked %>% rename(Label = data, Period = val)
periods

# ampl
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(0.12, 0.13, 0.11, 0.12, 0.11, 0.14, 0.07, 0.06, 0.06)
stds <- c(0.0151, 0.00835, 0.0214, 0.0242, 0.0226, 0.0130, 0.0130, 0.00835, 0.01)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to update the values
faked$val[faked$val < 0] <- 0 - faked$val[faked$val < 0]


amplitudes <- faked %>% rename(Label = data, Amplitude = val)
amplitudes

#phases
labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(3.5, 9, 15, 3.6, 7, 13.8, 2.5, 5.5, 8)
stds <- c(0.976, 1.12, 2, 1.5, 0.8, 0.7, 0.9, 3, 1.2)

faked <- series(labels, means, stds, 8)
faked

# Use dplyr to update the values
faked$val[faked$val < 0] <- 24 - faked$val[faked$val < 0]
faked$val[faked$val > 24] <- faked$val[faked$val < 24] - 24

phases <- faked %>% rename(Label = data, Phase = val)
phases

labels <- c('WT LHY', 'WT PRR5', 'WT TOC1','prr79 LHY', 'prr79 PRR5', 'prr79 TOC1','elf4 LHY', 'elf4 PRR5', 'elf4 TOC1')
means <- c(0.2, 0.27, 0.18, 0.14, 0.15, 0.12, 0.42, 0.38, 0.4)
stds <- c(0.04, 0.02, 0.0214, 0.02, 0.03, 0.025, 0.12, 0.15, 0.13)

faked <- series(labels, means, stds, 8)
faked

faked$val[faked$val < 0] <- 0 - faked$val[faked$val < 0]
raes <- faked %>% rename(Label = data, RAE = val)
raes


data <- periods %>%
        cbind( select(amplitudes, Amplitude)) %>%
        cbind( select(phases, Phase)) %>%
        cbind( select(raes, RAE)) %>%
        separate(Label,into=c("GENOTYPE","MARKER"), sep = " ", remove=FALSE) 


data

write_csv(data, "short_days_ppa.csv")


```

